### PR TITLE
Changes to suitcaseext that might be beneficial for suitcase

### PR DESCRIPTION
**Pull request by Kristi-Elmore**
Not all of these commits are suitable for a pull request - please reference the following commits that might be beneficial for suitcase

commit 99d465f
commit 690ab76
commit 1b9cd9c
commit 3bff298
commit 3ed82cf
commit 671f040
commit 4c7b5ac
commit b55b172

### CODE REVIEW

**Comment by hofmockel** [comment]
Great. I will look when I get a chance.

Pull-Requests are accepted as “all or nothing” so ...
In the future, more pull-requests is much easier than just one big one.
Please continue to submit simple pull-requests that I can easily accept, like a simple css change in one file, for instance.

Thank you so much for participating. More soon. Stop by some time if you like.

Michael Hofmockel
P: 515.450.9416
Email: michael.hofmockel@gmail.com | Skype: michael.hofmockel | Twitter: @hofmockel
Address: 2413 Kingston Dr., Ames, Iowa 50010, USA

**Comment by Kristi-Elmore** [comment]
Sorry Michael - I didn't realize that until I had done all of the changes and tried to submit a pull request of the commits I wanted to submit to you.  I will definitely not do that in the future.

Kristi Elmore
ISU Extension IT

**Comment by hofmockel** [comment]
No worries, let’s keep working together on this. ;p

Michael Hofmockel
P: 515.450.9416
Email: michael.hofmockel@gmail.com | Skype: michael.hofmockel | Twitter: @hofmockel
Address: 2413 Kingston Dr., Ames, Iowa 50010, USA

**Comment by rlfrahm** [comment]
Hi @Kristi-Elmore,

I think you are going to find that changing the stylesheet and javascript object names is going to create a headache for you when attempting to sync your fork with ours. I think the best thing for you to do would be to have your suitcase be a sub theme of suitcase and just extend what is already there. That would you avoid merge conflicts.

**Pull request closed without merging**
